name: Dependency Scan

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main", "github-ci"]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Audit root
        run: |
          npm audit --audit-level=moderate --json > audit-root.json
          cat audit-root.json | jq '.metadata.vulnerabilities'

      - name: Audit apps/web
        working-directory: apps/web
        run: |
          npm ci
          npm audit --audit-level=moderate --json > ../..//audit-web.json
          cat ../..//audit-web.json | jq '.metadata.vulnerabilities'

      - name: Audit apps/api
        working-directory: apps/api
        run: |
          npm ci
          npm audit --audit-level=moderate --json > ../..//audit-api.json
          cat ../..//audit-api.json | jq '.metadata.vulnerabilities'

      - name: Upload audit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audit-reports
          path: |
            audit-root.json
            audit-web.json
            audit-api.json

