name: security-config

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main", "github-ci"]

jobs:
  security-config:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root deps
        run: npm ci

      - name: Check for sensitive files and patterns
        run: |
          echo "Checking for sensitive files..."
          if [ -f ".env" ]; then echo "⚠️ Warning: .env file found in repository"; fi
          if [ -f "config/secrets.json" ]; then echo "⚠️ Warning: secrets.json file found in repository"; fi
          # Check for hardcoded secrets patterns (ignores tests/examples)
          if grep -r "password.*=" --include="*.ts" --include="*.js" --include="*.json" . | grep -v "test" | grep -v "example"; then
            echo "⚠️ Warning: Potential hardcoded passwords found"
          fi
          if grep -r "api[_-]?key.*=" --include="*.ts" --include="*.js" --include="*.json" . | grep -v "test" | grep -v "example"; then
            echo "⚠️ Warning: Potential hardcoded API keys found"
          fi

      - name: Audit root (fail on high)
        run: |
          echo "Checking package.json for security issues..."
          if npm audit --audit-level high --json | jq -e '.vulnerabilities | length > 0' > /dev/null; then
            echo "❌ High severity vulnerabilities found" && exit 1
          else
            echo "✅ No high severity vulnerabilities found"
          fi

      - name: Audit apps/web (fail on high)
        working-directory: apps/web
        run: |
          npm ci
          if npm audit --audit-level high --json | jq -e '.vulnerabilities | length > 0' > /dev/null; then
            echo "❌ High severity vulnerabilities found (web)" && exit 1
          else
            echo "✅ No high severity vulnerabilities found (web)"
          fi

      - name: Audit apps/api (fail on high)
        working-directory: apps/api
        run: |
          npm ci
          if npm audit --audit-level high --json | jq -e '.vulnerabilities | length > 0' > /dev/null; then
            echo "❌ High severity vulnerabilities found (api)" && exit 1
          else
            echo "✅ No high severity vulnerabilities found (api)"
          fi

