name: Validate Workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate workflow syntax
        run: |
          echo "Validating workflow files..."
          for workflow in .github/workflows/*.yml; do
            if [ -f "$workflow" ]; then
              echo "Checking $workflow..."
              # Basic YAML syntax check
              if ! python3 -c "import yaml; yaml.safe_load(open('$workflow'))" 2>/dev/null; then
                echo "❌ Invalid YAML syntax in $workflow"
                exit 1
              else
                echo "✅ Valid YAML syntax in $workflow"
              fi
            fi
          done

      - name: Check workflow structure
        run: |
          echo "Checking workflow structure..."
          for workflow in .github/workflows/*.yml; do
            if [ -f "$workflow" ]; then
              echo "Analyzing $workflow..."
              
              # Check for required fields
              if ! grep -q "name:" "$workflow"; then
                echo "❌ Missing 'name' field in $workflow"
                exit 1
              fi
              
              if ! grep -q "on:" "$workflow"; then
                echo "❌ Missing 'on' field in $workflow"
                exit 1
              fi
              
              if ! grep -q "jobs:" "$workflow"; then
                echo "❌ Missing 'jobs' field in $workflow"
                exit 1
              fi
              
              echo "✅ Basic structure valid in $workflow"
            fi
          done

      - name: Check for common issues
        run: |
          echo "Checking for common workflow issues..."
          
          # Check for hardcoded secrets
          if grep -r "password\|secret\|token" .github/workflows/ | grep -v "secrets\." | grep -v "GITHUB_TOKEN"; then
            echo "⚠️ Warning: Potential hardcoded secrets found in workflows"
          fi
          
          # Check for proper secret usage
          if grep -r "secrets\." .github/workflows/ | grep -v "GITHUB_TOKEN"; then
            echo "✅ Proper secret usage detected"
          fi
          
          # Check for proper Node.js version usage
          if grep -r "node-version" .github/workflows/ | grep -v "20"; then
            echo "⚠️ Warning: Non-standard Node.js version detected"
          fi
          
          echo "✅ Workflow validation completed"
