# This file contains workflow settings and configurations
# It's not a workflow itself but contains shared configurations

# Common environment variables used across workflows
env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'
  
# Common step configurations
steps:
  checkout:
    uses: actions/checkout@v4
    with:
      fetch-depth: 0  # For full git history when needed
  
  setup-node:
    uses: actions/setup-node@v4
    with:
      node-version: ${{ env.NODE_VERSION }}
      cache: 'npm'
  
  install-deps:
    run: npm ci
  
  generate-prisma:
    run: npm run prisma:generate
    working-directory: apps/api

# Common job configurations
jobs:
  postgres-service:
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: sarradabet_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

# Common environment variables for testing
test-env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sarradabet_test
  DIRECT_URL: postgresql://postgres:postgres@localhost:5432/sarradabet_test
  NODE_ENV: test

# Common cache configurations
cache:
  turbo:
    path: .turbo
    key: ${{ runner.os }}-turbo-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx') }}
    restore-keys: |
      ${{ runner.os }}-turbo-${{ hashFiles('**/package-lock.json') }}-
  
  node-modules:
    path: node_modules
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-

# Common file change patterns
file-patterns:
  api:
    - 'apps/api/**'
    - 'packages/**'
    - 'package.json'
    - 'turbo.json'
  
  web:
    - 'apps/web/**'
    - 'packages/**'
    - 'package.json'
    - 'turbo.json'
  
  packages:
    - 'packages/**'
    - 'package.json'
    - 'turbo.json'
  
  root:
    - 'package.json'
    - 'turbo.json'
    - '.github/**'

# Common deployment configurations
deployment:
  platforms:
    railway:
      token-secret: RAILWAY_TOKEN
      service: api
    
    vercel:
      token-secret: VERCEL_TOKEN
      org-id-secret: VERCEL_ORG_ID
      project-id-secret: VERCEL_PROJECT_ID
    
    netlify:
      auth-token-secret: NETLIFY_AUTH_TOKEN
      site-id-secret: NETLIFY_SITE_ID
    
    aws:
      access-key-secret: AWS_ACCESS_KEY_ID
      secret-key-secret: AWS_SECRET_ACCESS_KEY
      region: us-east-1

# Common notification configurations
notifications:
  success-emoji: '✅'
  failure-emoji: '❌'
  warning-emoji: '⚠️'
  info-emoji: 'ℹ️'
